apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.ingress.name}}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{.Values.ingress.host}}
    http: 
      paths:
      - path: /client-ip
        pathType: Prefix
        backend:
          service:
            name: {{.Values.service.name}}
            port:
              number: {{.Values.service.port}}

      - path: /client-ip/list
        pathType: Prefix
        backend:
          service:
            name: {{.Values.service.name}}
            port:
              number: {{.Values.service.port}}

  tls:
  - hosts:
      - {{.Values.ingress.host}}
    secretName: letsencrypt-prod