apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  selector:
    app.kubernetes.io/name: {{.Values.deployment.labels}}
  ports:
    - protocol: {{.Values.service.protocol}}
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}